apiVersion: v1
kind: Secret
metadata:
  labels:
    backupType: {{ .Values.threefoldVdc.backup | quote }}
  name: {{ .Release.Name }}-auth
data:
  account_password: {{ .Values.account_password | quote }}