graph LR
 initiator -->|Sign| guardian1
 initiator -->|Sign| guardian2
 guardian2 -->|Signed tx| initiator 
 initiator -->|Sign| guardian3
 initiator -->|Sign| guardian4
 guardian4 -->|Signed tx| initiator 
 initiator -->|Sign| guardian5
 guardian5 -->|Signed tx| initiator 
 initiator -->|Sign| guardian6
 guardian6 -->|Signed tx| initiator 
 initiator -->|Sign| guardian7
 initiator -->|Sign| guardian8
 guardian8 -->|Signed tx| initiator
 initiator -->|Sign| guardian9
 guardian9 -->|Signed tx| initiator
 initiator -->|Submit| Stellar{Stellar network}

 
 