apiVersion: v1
kind: PersistentVolume
metadata:
  name: bridge-volume-{{ .Release.Name }}
  labels:
    backupType: {{ .Values.threefoldVdc.backup | quote }}
    type: local
spec:
  storageClassName: local-path
  capacity:
    storage: {{ .Values.volume.size }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.volume.hostPath }}