[DOCUMENTATION]
ORG_NAME="Threefold foundation"
ORG_URL="https://threefold.io"
ORG_LOGO="https://threefoldfoundation.github.io/tft/tft_icon.png"
ORG_PHYSICAL_ADDRESS="Dubai, UAE"
ORG_GITHUB="threefoldfoundation"
ORG_OFFICIAL_EMAIL="support@threefold.io"
ORG_SUPPORT_EMAIL="support@threefold.io"

[[CURRENCIES]]
code = "TFT"
issuer = "GBOVQKJYHXRR3DX6NOX2RRYFRCUMSADGDESTDNBDS6CDVLGVESRTAC47"
display_decimals = 2
name = "Threefold Token"
desc = "A digital currency used to buy autonomous and decentralized Internet services (compute, storage, and application) on the ThreeFold Network"
image = "https://threefoldfoundation.github.io/tft/tft_icon.png"

[[CURRENCIES]]
code = "TFTA"
issuer = "GBUT4GP5GJ6B3XW5PXENHQA7TXJI5GOPW3NF4W3ZIW6OOO4ISY6WNLN2"
display_decimals = 2
name = "Threefold Token"
desc = "A digital currency used to buy autonomous and decentralized Internet services (compute, storage, and application) on the ThreeFold Network"
image = "https://threefoldfoundation.github.io/tft/tft_icon.png"
