[[CURRENCIES]]
code="TFT"
issuer="GBOVQKJYHXRR3DX6NOX2RRYFRCUMSADGDESTDNBDS6CDVLGVESRTAC47"
display_decimals=2 
name="ThreeFold Token"
desc="A digital currency used to buy autonomous and decentralized Internet services (compute, storage, and application) on the ThreeFold Network"
image="https://www.threefold.io/assets/3fold_icon.png"

[[CURRENCIES]]
code="FreeTFT"
issuer="GCBGS5TFE2BPPUVY55ZPEMWWGR6CLQ7T6P46SOFGHXEBJ34MSP6HVEUT"
display_decimals=2 
name="Free ThreeFold Token"
desc="A free digital currency used to buy free autonomous and decentralized Internet services (compute, storage, and application) on the ThreeFold Network"
image="https://www.threefold.io/assets/3fold_icon.png"
