apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tftservices.fullname" . }}
  labels:
    {{- include "tftservices.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "tftservices.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "tftservices.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "tftservices.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: ACTIVATION_WALLET_SECRET
              valueFrom:
                secretKeyRef:
                  name: tftservices-config
                  key: ACTIVATION_WALLET_SECRET
            - name: TXFUNDING_WALLET_SECRET
              valueFrom:
                secretKeyRef:
                  name: tftservices-config
                  key: TXFUNDING_WALLET_SECRET
            - name: VESTING_WALLET_SECRET
              valueFrom:
                secretKeyRef:
                  name: tftservices-config
                  key: VESTING_WALLET_SECRET
            - name: TFT_SERVICES_NETWORK
              value:  {{ .Values.tftservicesnetwork }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
            - name: https
              containerPort: 443
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
