[DOCUMENTATION]
ORG_NAME="Threefold foundation"
ORG_URL="https://testnet.threefold.io"
ORG_LOGO="https://threefoldfoundation.github.io/tft/tft_icon.png"
ORG_PHYSICAL_ADDRESS="Dubai, UAE"
ORG_GITHUB="threefoldfoundation"
ORG_OFFICIAL_EMAIL="support@testnet.threefold.io"
ORG_SUPPORT_EMAIL="support@testnet.threefold.io"

[[CURRENCIES]]
code = "TFT"
issuer = "GA47YZA3PKFUZMPLQ3B5F2E3CJIB57TGGU7SPCQT2WAEYKN766PWIMB3"
display_decimals = 2
name = "Threefold Token"
desc = "A digital currency used to buy autonomous and decentralized Internet services (compute, storage, and application) on the ThreeFold Network"
image = "https://threefoldfoundation.github.io/tft/tft_icon.png"

[[CURRENCIES]]
code = "TFTA"
issuer = "GB55A4RR4G2MIORJTQA4L6FENZU7K4W7ATGY6YOT2CW47M5SZYGYKSCT"
display_decimals = 2
name = "Threefold Token"
desc = "A digital currency used to buy autonomous and decentralized Internet services (compute, storage, and application) on the ThreeFold Network"
image = "https://threefoldfoundation.github.io/tft/tft_icon.png"