[[CURRENCIES]]
code="TFT"
issuer="GA47YZA3PKFUZMPLQ3B5F2E3CJIB57TGGU7SPCQT2WAEYKN766PWIMB3"
display_decimals=2 
name="ThreeFold Token"
desc="A digital currency used to buy autonomous and decentralized Internet services (compute, storage, and application) on the ThreeFold Network"
image="https://www2.threefold.io/assets/3fold_icon.png"


[[CURRENCIES]]
code="FreeTFT"
issuer="GBLDUINEFYTF7XEE7YNWA3JQS4K2VD37YU7I2YAE7R5AHZDKQXSS2J6R"
display_decimals=2 
name="Free ThreeFold Token"
desc="A free digital currency used to buy free autonomous and decentralized Internet services (compute, storage, and application) on the ThreeFold Network"
image="https://www.threefold.io/assets/3fold_icon.png"
