@startuml newaccountactivation

title Activating a new account 

actor User
participant Wallet
participant "Activation service" as as
participant "SMS Service" as smss
participant "Stellar network" as sn

User-> Wallet: Create new account
activate Wallet
Wallet -> Wallet: Generate Keypair
Wallet-> as: Address activation Request(Address)
activate as
as-> as: Generate unique activation code \n store code/address combination
as->Wallet : activation code + phone numbers
deactivate as

Wallet->User : show code + phonenumber
deactivate Wallet
User ->smss: Send SMS with code
smss-> as: smsreceived(code,phonenumber)
as-> sn: Activate account
Wallet -> sn: Can check if account is active
@enduml