name: Publish Docker images

on:
  release:
    types: [published]

jobs:
  build-and-push:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for tftservices
        id: metatftservices
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/threefoldfoundation/tftservices
          tags: |
            type=semver,pattern={{version}}

      - name: Build and push tftservices
        uses: docker/build-push-action@v3
        with:
          push: true
          no-cache: true
          file: docker/tftservices/Dockerfile
          tags: ${{ steps.metatftservices.outputs.tags }}
          labels: ${{ steps.metatftservices.outputs.labels }}

      - name: Extract metadata for tftstatistics
        id: metatftstatistics
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/threefoldfoundation/tftstatistics
          tags: |
            type=semver,pattern={{version}}

      - name: Build and push tftstatistics
        uses: docker/build-push-action@v3
        with:
          push: true
          no-cache: true
          file: docker/tftstatistics/Dockerfile
          tags: ${{ steps.metatftstatistics.outputs.tags }}
          labels: ${{ steps.metatftstatistics.outputs.labels }}
